/**
 * RFC-ACL-022 — clés flag canoniques par module métier.
 * Activation manuelle par client via `ClientFeatureFlag` (cf. runbook).
 */
export const FLAG_KEYS = {
  ORG_OWNERSHIP_REQUIRED: 'ORG_OWNERSHIP_REQUIRED',
  ACCESS_DECISION_V2_PROJECTS: 'ACCESS_DECISION_V2_PROJECTS',
  ACCESS_DECISION_V2_BUDGETS: 'ACCESS_DECISION_V2_BUDGETS',
  ACCESS_DECISION_V2_CONTRACTS: 'ACCESS_DECISION_V2_CONTRACTS',
  ACCESS_DECISION_V2_PROCUREMENT: 'ACCESS_DECISION_V2_PROCUREMENT',
  ACCESS_DECISION_V2_STRATEGIC_VISION: 'ACCESS_DECISION_V2_STRATEGIC_VISION',
} as const;

export type FlagKey = (typeof FLAG_KEYS)[keyof typeof FLAG_KEYS];
