#!/usr/bin/env python3
"""
Consolidate all documentation files under ./docs into a single markdown file.

Output format:
 - One section per source file (with relative path)
 - The source content is embedded as a markdown fenced block
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


def iter_files(root: Path) -> list[Path]:
    # We only include regular files (no directories) and keep a deterministic sort.
    files: list[Path] = []
    for p in root.rglob("*"):
        if p.is_file():
            files.append(p)
    return sorted(files, key=lambda x: x.as_posix())


def main() -> int:
    parser = argparse.ArgumentParser(description="Consolidate docs/ into a single file.")
    parser.add_argument(
        "--docs-dir",
        default="docs",
        help="Directory to consolidate (default: docs)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output markdown path (default: <repo-root>/DOCS_CONSOLIDATED.md)",
    )
    parser.add_argument(
        "--encoding",
        default="utf-8",
        help="File encoding to use (default: utf-8)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent
    docs_dir = (repo_root / args.docs_dir).resolve()
    if not docs_dir.exists() or not docs_dir.is_dir():
        print(f"ERROR: docs dir not found: {docs_dir}", file=sys.stderr)
        return 2

    out_path = Path(args.output).resolve() if args.output else (repo_root / "DOCS_CONSOLIDATED.md")

    # Avoid accidental self-inclusion if the output is inside docs/.
    files = [p for p in iter_files(docs_dir) if p.resolve() != out_path]

    banner = (
        f"# Docs consolidated ({docs_dir.name})\n"
        f"Generated by `{Path(__file__).name}`.\n\n"
        f"- Source directory: `{docs_dir.as_posix()}`\n"
        f"- Files included: `{len(files)}`\n"
    )

    with out_path.open("w", encoding="utf-8") as f:
        f.write("<!-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. -->\n\n")
        f.write(banner + "\n")

        for idx, p in enumerate(files, start=1):
            rel = p.relative_to(docs_dir).as_posix()
            f.write("\n\n")
            f.write("<!-- ========================================================= -->\n")
            f.write(f"## {rel}\n")
            f.write("<!-- ========================================================= -->\n\n")

            try:
                content = p.read_text(encoding=args.encoding, errors="replace")
            except Exception as e:  # pragma: no cover
                f.write(f"~~~text\n[ERROR reading file: {e}]\n~~~\n")
                continue

            content_stripped = content.rstrip("\n")
            # Use `~~~` fences to minimize collision with triple-backticks inside docs.
            f.write("~~~text\n")
            f.write(content_stripped)
            f.write("\n~~~\n")

            # Tiny progress marker (useful for large doc sets).
            if idx % 10 == 0:
                f.write(f"\n<!-- consolidated: {idx}/{len(files)} -->\n")

    print(f"OK: wrote {out_path.as_posix()} ({len(files)} files).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

