export const COMPLIANCE_AUDIT_ACTION = {
  FRAMEWORK_CREATED: 'compliance.framework.created',
  FRAMEWORK_UPDATED: 'compliance.framework.updated',
  FRAMEWORK_ARCHIVED: 'compliance.framework.archived',
  FRAMEWORK_RESTORED: 'compliance.framework.restored',
  FRAMEWORK_ACTIVATED: 'compliance.framework.activated',
  REQUIREMENT_CREATED: 'compliance.requirement.created',
  STATUS_UPDATED: 'compliance.status.updated',
  EVIDENCE_CREATED: 'compliance.evidence.created',
  EVIDENCE_UPDATED: 'compliance.evidence.updated',
  EVIDENCE_VERSIONED: 'compliance.evidence.versioned',
  CAMPAIGN_CREATED: 'compliance.campaign.created',
  CAMPAIGN_OPENED: 'compliance.campaign.opened',
  CAMPAIGN_CLOSED: 'compliance.campaign.closed',
  CAMPAIGN_SNAPSHOT: 'compliance.campaign.snapshot',
  CAMPAIGN_IMPORT: 'compliance.campaign.evaluations_imported',
  CAMPAIGN_EXPORT: 'compliance.campaign.snapshot_exported',
  NA_REQUESTED: 'compliance.na.requested',
  NA_APPROVED: 'compliance.na.approved',
  NA_REJECTED: 'compliance.na.rejected',
  NA_CANCELLED: 'compliance.na.cancelled',
  CONTRIBUTION_CREATED: 'compliance.contribution.created',
  CONTRIBUTION_UPDATED: 'compliance.contribution.updated',
  GAP_CREATED: 'compliance.gap.created',
  GAP_UPDATED: 'compliance.gap.updated',
  GAP_REMEDIATION_LINKED: 'compliance.gap.remediation_linked',
} as const;

export const COMPLIANCE_AUDIT_RESOURCE_TYPE = {
  COMPLIANCE_FRAMEWORK: 'compliance_framework',
  COMPLIANCE_REQUIREMENT: 'compliance_requirement',
  COMPLIANCE_STATUS: 'compliance_status',
  COMPLIANCE_EVIDENCE: 'compliance_evidence',
  COMPLIANCE_CAMPAIGN: 'compliance_campaign',
  COMPLIANCE_CAMPAIGN_SNAPSHOT: 'compliance_campaign_snapshot',
  COMPLIANCE_NA_REQUEST: 'compliance_na_request',
  COMPLIANCE_CONTRIBUTION: 'compliance_contribution',
  COMPLIANCE_GAP: 'compliance_gap',
} as const;
